CREATE TABLE USERS(
ID CHAR(6) PRIMARY KEY,
PASSWORD VARCHAR2(20) NOT NULL,
NAME VARCHAR2(50) NOT NULL,
DEPID CHAR(4),
TEL VARCHAR2(20),
ROLE_CLASS CHAR(1)
);

CREATE TABLE STATUS(
CODE CHAR(1) PRIMARY KEY,
NAME VARCHAR2(30) NOT NULL
);

CREATE TABLE SOUKO(
ID CHAR(4) PRIMARY KEY,
NAME VARCHAR2(100) NOT NULL,
ADDRESS VARCHAR2(100)
);

CREATE TABLE DEPARTMENT(
ID CHAR(4) PRIMARY KEY,
NAME VARCHAR2(50) NOT NULL
);

CREATE TABLE CATEGORY(
ID CHAR(4) PRIMARY KEY,
NAME VARCHAR2(100) NOT NULL
);

CREATE TABLE SIZAI(
ID NUMBER PRIMARY KEY,
NAME VARCHAR2(200) NOT NULL,
NUM NUMBER(5, 0) NOT NULL,
SOUKO_ID CHAR(4),
CATEGORY_ID CHAR(4),
REQUEST_USER_ID CHAR(6),
REQUEST_DEPT_ID CHAR(4),
STATUS CHAR(1),
REQUEST_DATE DATE,
ORDER_DATE DATE,
DELIVERY_DATE DATE,
INSTORE_DATE DATE,
OUTSTORE_DATE DATE,
NOTE VARCHAR2(2000)
);


create sequence SIZAI_ID_SEQ
minvalue 1
maxvalue 999999999
start with 1
increment by 1 
nocache;

create or replace trigger SIZAI_ID_AUTOINC
before insert on SIZAI
for each row
begin
select SIZAI_ID_SEQ.nextval into :new.ID from dual;
end;

COMMENT ON TABLE USERS IS 'ユーザマスタ';
COMMENT ON TABLE STATUS IS '状態マスタ';
COMMENT ON TABLE SOUKO IS '倉庫マスタ';
COMMENT ON TABLE DEPARTMENT IS '部署マスタ';
COMMENT ON TABLE CATEGORY IS '資材カテゴリ';
COMMENT ON TABLE SIZAI IS '資材マスタ';

COMMENT ON COLUMN SALGRADE.RANK  IS 'ランク';

ALTER TABLE USERS
ADD CONSTRAINT user_dep_fk
FOREIGN KEY (DEPID)
REFERENCES DEPARTMENT(ID);

ALTER TABLE SIZAI
ADD CONSTRAINT sizai_souko_fk
FOREIGN KEY (SOUKO_ID)
REFERENCES SOUKO(ID);

ALTER TABLE SIZAI
ADD CONSTRAINT sizai_cata_fk
FOREIGN KEY (CATEGORY_ID)
REFERENCES CATEGORY(ID);

ALTER TABLE SIZAI
ADD CONSTRAINT sizai_cata_fk
FOREIGN KEY (CATEGORY_ID)
REFERENCES CATEGORY(ID);

ALTER TABLE SIZAI
ADD CONSTRAINT sizai_dept_fk
FOREIGN KEY (REQUEST_DEPT_ID)
REFERENCES DEPARTMENT(ID);

ALTER TABLE SIZAI
ADD CONSTRAINT sizai_user_fk
FOREIGN KEY (REQUEST_USER_ID)
REFERENCES USERS(ID);

INSERT INTO SIZAI (NAME, NUM, SOUKO_ID, CATEGORY_ID, REQUEST_USER_ID, REQUEST_DEPT_ID, STATUS, REQUEST_DATE, ORDER_DATE, DELIVERY_DATE, INSTORE_DATE, OUTSTORE_DATE, NOTE)
VALUES ('TV', '5', NULL, NULL, NULL, NULL, '1', SYSDATE, NULL, NULL, NULL, NULL, NULL);
